#ifndef MESSAGE_HPP
# define MESSAGE_HPP


#define RPL_WELCOME				001
#define RPL_JOINCHANNEL			002
#define RPL_PART				003
#define RPL_MODE				004
#define RPL_TOPIC				332
#define RPL_NOTOPIC				331
#define RPL_NAMREPLY			353
#define RPL_ENDOFNAMES			366
#define ERR_SERVICESFULL		471
#define ERR_BADCHANNELKEY		475
#define ERR_NOTONCHANNEL		442
#define ERR_NOSUCHCHANNEL		403
#define ERR_MSGTOOLONG			414
#define ERR_NICKNAMEINUSE		433
#define ERR_USERONCHANNEL		443
#define ERR_PASSWDMISMATCH		464
#define ERR_NEEDMOREPARAMS		461
#define RPL_HELPTXT				705


# endif