#ifndef MESSAGE_HPP
# define MESSAGE_HPP

#define RPL_WELCOME				1
#define RPL_JOINCHANNEL			2
#define RPL_PART				3
#define RPL_MODE				4
#define RPL_QUIT				5
#define RPL_NICK				6
#define RPL_PING				7
#define RPL_PRIVMSG				8
#define RPL_LISTSTART			321
#define RPL_LIST				322
#define RPL_LISTEND				323
#define RPL_TOPIC				332
#define RPL_NOTOPIC				331
#define RPL_NAMREPLY			353
#define RPL_ENDOFNAMES			366
#define ERR_NOSUCHNICK			401
#define ERR_NOSUCHCHANNEL		403
#define ERR_NORECIPIENT			411
#define ERR_NOTEXTTOSEND		412
#define ERR_MSGTOOLONG			414
#define ERR_TOOMANYTARGETS		417
#define ERR_UNKNOWNCOMMAND		421
#define ERR_NICKNAMEINUSE		433
#define ERR_USERNOTINCHANNEL	441
#define ERR_NOTONCHANNEL		442
#define ERR_USERONCHANNEL		443
#define ERR_NEEDMOREPARAMS		461
#define ERR_PASSWDMISMATCH		464
#define ERR_SERVICESFULL		471
#define ERR_BADCHANNELKEY		475
#define RPL_HELPTXT				705

# endif